### ISSUE TITLE
Ver Alto del Footer, elementos descolocados y fuera de lugar

### ISSUE THREAD

**Issue by CVazquezOpalka** [Lostovayne/shop.co-ecommerce#16]
Se debe realizar vericacion del footerm dado que los mismos se estan rompiendo en monitor de alta resolucion.
Se adjuntan capturas de pantalla.
![image](https://github.com/Lostovayne/shop.co-ecommerce/assets/106532109/e4d926ab-7f47-458a-9e32-af479dd5e24b)

**Comment by Lostovayne** [comment]
esto quedo listo y corregido
